#!/usr/bin/env python3
import os
import requests
import sys


head="==============>> BRUTE BY ANNOMY <<===============\nVersion: 2.0\n"
usage="Usage: "+sys.argv[0]+" http://test.com/ words.txt"



if len(sys.argv)==1:
	print(usage)
	exit()
url=sys.argv[1]
head=head+"Url: "+url+"\n"
found="--------------------------------------------------\nFound:-\n"
test=""
ln=0
out="found.txt"								# outfile to write



if url=="-h" or url=="--help":						# printing help
	print(usage)
	exit()


if len(sys.argv)==2:							# checking number of argument given
	dir="/usr/share/wordlists/dirb/common.txt"
elif len(sys.argv)==3:
	dir=sys.argv[2]
else:
	print(usage)
	exit()

file=open(dir,"r")							# opening file to read
head=head+"File: "+dir+"\n"
run=True

def update():								# update function to print latest data
	os.system("clear")
	print(head+found+test)

def end():								# end function to write data to file
	outfile=open(out,"w")
	outfile.write(head)
	outfile.write(found)
	outfile.close()

update()
while run:								# main program
	ln +=1
	str=""
	l=file.read(1)
	while not (l=="\n" or l==""):
		str +=l
		l=file.read(1)
	if l=="":
		found=found+"------------------- COMPLETED --------------------\n"
		test=''
		update()
		end()
		run=False
	if (ln%10==0):
		test="\nTesting:-\n"+str+"\n"
		update()
	atk=url+str
	r=requests.get(atk)
	if not (r.status_code==404):
		found=found+str+"\n"
		update()
